root: ./docs/

​structure:  
    readme: README.md  
    summary: SUMMARY.md​

redirects:  
    quickstart: quickstart.md
    quickstart/installation: quickstart.md
    quickstart/authentication: quickstart.md
    quickstart/connect-a-device: quickstart.md
    quickstart/your-first-device-api-call: quickstart.md
    quickstart/going-live: quickstart.md