root: 
  ./docs/
redirects:
  quickstart/get-api-key: quickstart.md
  quickstart/installation: quickstart.md
  quickstart/authentication: quickstart.md
  quickstart/connect-a-device: quickstart.md
  quickstart/your-first-device-api-call: quickstart.md
  quickstart/going-live: quickstart.md
